---
sudo: false
language: ruby
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.1
  - jruby-1.7.26
  - jruby-9.1.8.0
script: bundle exec rake
matrix:
  allow_failures:
    - rvm: jruby-1.7.26
    - rvm: jruby-9.1.8.0
